fwheudiconv runs but full gear crashed
can revert back to main branch if need be but this patch was supposed to 
fix  #1 by adding fwheudiconv. fwheudiconv ran successfully but qsiprep 
failed

diff --git a/run b/run
--- a/run
+++ b/run
@@ -340,32 +340,32 @@ elif [[ $config_save_outputs == 'true' ]] ; then
   time zip -q -r "$GEAR_OUTPUT_DIR"/debug_qsiprep_work_"$ANALYSIS_ID" $(basename "$WORKING_DIR")
   chmod -R 777 $GEAR_OUTPUT_DIR
 
-################################################################################
-# COPY ANALYSIS TO PROJECT LEVEL IF MULTI-SESSION
-#   Use Python SDK to accomplish this task
+  ################################################################################
+  # COPY ANALYSIS TO PROJECT LEVEL IF MULTI-SESSION
+  #   Use Python SDK to accomplish this task
 
-/usr/local/miniconda/bin/python ${FLYWHEEL_BASE}/move_to_project.py
-if [[ $? != 0 ]]; then
-  echo "$CONTAINER  Problem resolving multi-session structure! Exiting (1)"
-  exit 1
-fi
+  /usr/local/miniconda/bin/python ${FLYWHEEL_BASE}/move_to_project.py
+  if [[ $? != 0 ]]; then
+    echo "$CONTAINER  Problem resolving multi-session structure! Exiting (1)"
+    exit 1
+  fi
 
 elif [[ $config_save_outputs == 'true' ]] ; then
-echo "$CONTAINER  Error occurred. Config 'save_outputs' set to true. Zipping up outputs."
-cd "$GEAR_OUTPUT_DIR"
-time zip -q -r "$GEAR_OUTPUT_DIR"/debug_fmriprep_"$ANALYSIS_ID"  $(basename "$FMRIPREP_OUTPUT_DIR")
-time zip -q -r "$GEAR_OUTPUT_DIR"/debug_fmriprep_work_"$ANALYSIS_ID" $(basename "$WORKING_DIR")
-chmod -R 777 $GEAR_OUTPUT_DIR
+  echo "$CONTAINER  Error occurred. Config 'save_outputs' set to true. Zipping up outputs."
+  cd "$GEAR_OUTPUT_DIR"
+  time zip -q -r "$GEAR_OUTPUT_DIR"/debug_fmriprep_"$ANALYSIS_ID"  $(basename "$FMRIPREP_OUTPUT_DIR")
+  time zip -q -r "$GEAR_OUTPUT_DIR"/debug_fmriprep_work_"$ANALYSIS_ID" $(basename "$WORKING_DIR")
+  chmod -R 777 $GEAR_OUTPUT_DIR
 
-################################################################################
-# COPY ANALYSIS TO PROJECT LEVEL IF MULTI-SESSION
-#   Use Python SDK to accomplish this task
+  ################################################################################
+  # COPY ANALYSIS TO PROJECT LEVEL IF MULTI-SESSION
+  #   Use Python SDK to accomplish this task
 
-/usr/local/miniconda/bin/python ${FLYWHEEL_BASE}/move_to_project.py
-if [[ $? != 0 ]]; then
-  echo "$CONTAINER  Problem resolving multi-session structure! Exiting (1)"
-  exit 1
-fi
+  /usr/local/miniconda/bin/python ${FLYWHEEL_BASE}/move_to_project.py
+  if [[ $? != 0 ]]; then
+    echo "$CONTAINER  Problem resolving multi-session structure! Exiting (1)"
+    exit 1
+  fi
 
 else
   echo "$CONTAINER  Errors encountered during execution. Save outputs config not set. Cleaning up and exiting."
